# Generated by Django 4.2 on 2025-01-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(default='안녕하세요', max_length=300, null=True),
        ),
    ]
